data:
  name: PerturbationDataModule
  kwargs:
    toml_config_path: examples/fewshot.toml
    embed_key: X_hvg
    output_space: all
    pert_rep: onehot
    basal_rep: sample
    num_workers: 8
    pin_memory: true
    n_basal_samples: 1
    basal_mapping_strategy: random
    should_yield_control_cells: true
    batch_col: batch
    pert_col: target_gene
    cell_type_key: null
    control_pert: non-targeting
    map_controls: true
    perturbation_features_file: null
    store_raw_basal: false
    int_counts: false
    barcode: true
  output_dir: null
  debug: true
model:
  name: PertSets
  checkpoint: null
  device: cuda
  kwargs:
    cell_set_len: 64
    extra_tokens: 1
    decoder_hidden_dims:
    - 1024
    - 1024
    - 512
    blur: 0.05
    hidden_dim: 256
    loss: energy
    confidence_token: false
    n_encoder_layers: 4
    n_decoder_layers: 4
    predict_residual: true
    freeze_pert_backbone: false
    finetune_vci_decoder: false
    residual_decoder: false
    batch_encoder: false
    use_batch_token: false
    nb_decoder: false
    decoder_loss_weight: 1.0
    use_basal_projection: false
    mask_attn: false
    distributional_loss: energy
    regularization: 0.0
    init_from: null
    transformer_backbone_key: GPT2
    transformer_backbone_kwargs:
      max_position_embeddings: 64
      n_positions: 64
      hidden_size: 256
      n_embd: 256
      n_layer: 8
      n_head: 8
      resid_pdrop: 0.0
      embd_pdrop: 0.0
      attn_pdrop: 0.0
      use_cache: false
training:
  wandb_track: true
  weight_decay: 0.0005
  batch_size: 8
  lr: 0.0001
  max_steps: 20000
  train_seed: 42
  val_freq: 2000
  ckpt_every_n_steps: 100
  gradient_clip_val: 10
  loss_fn: mse
  devices: 1
  strategy: auto
  use_mfu: true
  mfu_kwargs:
    available_flops: 60000000000000.0
    use_backward: true
    logging_interval: 10
    window_size: 2
  cumulative_flops_use_backward: true
wandb:
  entity: your_entity_name
  project: state
  local_wandb_dir: ./wandb_logs
  tags:
  - vcc_fewshot
name: vcc_fewshot
output_dir: ./checkpoints
use_wandb: true
overwrite: false
return_adatas: false
pred_adata_path: null
true_adata_path: null
